name: C/C++ CI

on: 
  push:
    branches: 
      - master



jobs:
  build:
    strategy:
      matrix:
        compiler: [gcc]
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run CMake
      env:
        CC: ${{ matrix.compiler }}
      run: cmake --build .
