name: C/C++ CI

on: 
  push:
    branches: 
      - master



jobs:
  build:
    strategy:
      matrix:
        compiler: [gcc]
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: CMake build
      run: |
        rm -rf build/
        mkdir build
        cd build
        cmake ../v6 
    - name: Run CMake
      env:
        CC: ${{ matrix.compiler }}
      run: |
        cd build/
        cmake --build .
    - name: test initfs
      run: |
        cd build/
        ./V6FileSystem
        initfs v6 500000 1000
        q
